<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="Desk-67A" name="automation_Testcases.SignIn_Test" tests="9" failures="0" timestamp="24 Aug 2017 06:44:55 GMT" time="0.370" errors="1">
  <testcase name="SignIn_Successful_TC" time="0.000" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- SignIn_Successful_TC -->
  <testcase name="BeforeMethod" time="0.370" classname="automation_Testcases.SignIn_Test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Common_Utility.ExcelUtils.getRowContains(ExcelUtils.java:101)
	at automation_Testcases.SignIn_Test.BeforeMethod(SignIn_Test.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- BeforeMethod -->
  <testcase name="Invalid_EmailFormat_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- Invalid_EmailFormat_TC -->
  <testcase name="Blank_Email_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- Blank_Email_TC -->
  <testcase name="Unregistered_Email_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- Unregistered_Email_TC -->
  <testcase name="ForgotPassword_Navigate_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- ForgotPassword_Navigate_TC -->
  <testcase name="SignUp_Navigate_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- SignUp_Navigate_TC -->
  <testcase name="Blank_Password_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- Blank_Password_TC -->
  <testcase name="Incorrect_Password_TC" classname="automation_Testcases.SignIn_Test">
    <skipped/>
  </testcase> <!-- Incorrect_Password_TC -->
</testsuite> <!-- automation_Testcases.SignIn_Test -->
